### PR TITLE
Adding override for custom settings

### PR DESCRIPTION
**Pull request by jfyles**
We have interactive notifications in our app and need to supply custom settings to register for notifications. I preserved old functionality, and added an overload. Want to take a look and merge?

Thanks!
Justin

### CODE REVIEW

**Comment by jfyles** [comment]
Hey @jlaws, did you have a chance to take a look? I'd love to get this mainlined before we release the next version of our app.

Thanks!

**Comment by jlaws** [comment]
Unfortunately your CL only works for iOS 8+, whereas the library is designed to support iOS 7+.  I will look into ways to achieve what you want, but in a way it still supports older ios version.  Will try and post a new pod later today for you.

**Comment by jlaws** [comment]
@jfyles Alright, just pushed v2.2.3 which supports custom user notification types on both iOS 7 and 8.  Once you obtain the JLNotificationPermission sharedInstance you can set these properties on it:


/**
 * For iOS 8 set this for the notification types you want to register for.  If not set, it uses
 * Alert, Badge, and Sound notification types.
 */
@property(nonatomic) UIUserNotificationSettings *userNotificationSettings;

/**
 * For iOS 7 set this for the notification types you want to register for.  If not set, it uses
 * Alert, Badge, and Sound notification types.
 */
@property(nonatomic) UIRemoteNotificationType remoteNotificationType;

They need to be set before authorizing.  Let me know if you have any issues.

**Comment by jfyles** [comment]
Fantastic! Works like a charm.

Thanks!

Justin

**Pull request closed without merging**
